services:
  - type: web
    name: green-leaf-backend
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api:app --host 0.0.0.0 --port 10000
    pythonVersion: 3.10
